[package]
name = "paraxis"
authors = ["Glenn Wallace glennw-coding@proton.me"]
description = "A simple to use spatial datastructure crate."
version = "0.10.8"
edition = "2024"
keywords = ["linear-algebra", "maths", "numpy"]
categories = ["mathematics"]
license = "Apache-2.0"
repository = "https://codeberg.org/Stack-Syndicate/paraxis"

[[bench]]
name = "trees"
harness = false

[[bench]]
name = "linalg"
harness = false

[dependencies]
itertools = "0.15.0"
num-complex = "0.4.6"
num-traits = "0.2.19"
thiserror = "2.0.19"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
rand = "0.10.2"
