[package]
name = "paraxis"
authors = ["Glenn Wallace glennw-coding@proton.me"]
description = "A simple rock-solid mathematics library."
version = "0.8.18"
edition = "2024"
keywords = ["maths", "gpu", "vectorization", "linear-algebra", "numpy"]
categories = ["mathematics"]
license = "MIT"
repository = "https://github.com/glennw-mt/paraxis"

[dependencies]
dashmap = {version = "6.1.0", defualt-feautures=false}

[dev-dependencies]
nalgebra = "0.34.1"
