name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: codeberg-small-lazy
    container:
      image: rust:slim-bookworm
    steps:
      - name: Install node
        run: |
          apt-get update && apt-get install nodejs build-essential g++ cmake -y
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          rustup component add clippy
      - name: Check Code Quality
        run: |
          cargo clippy --workspace --all-targets -- -D warnings
      - name: Run Test Suite
        run: |
          cargo test --workspace --all-targets
      - name: Publish to Codeberg
        env:
          CARGO_REGISTRIES_CODEBERG_INDEX: "sparse+https://codeberg.org/api/packages/${{ github.repository_owner }}/cargo/"
          CARGO_REGISTRIES_CODEBERG_TOKEN: "Bearer ${{ secrets.CODEBERG_PACKAGES }}"
        run: cargo publish --registry codeberg
      - name: Publish to Crates.IO
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO }}
        run: |
          cargo publish
